list = This is a little ipsum text with several \"is\". Is it really working?
search = is

default: go ruby

go:
	go run string_counter.go "$(list)" "$(search)"

ruby:
	./string_counter.rb "$(list)" "$(search)"
